[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
buildCommand = "echo 'Using Dockerfile'"
watchPatterns = [
    "requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
]